# Brownie configuration file
# https://eth-brownie.readthedocs.io/en/stable/config.html
dotenv: .env 
networks:
    default: development

pytest:
    cmd: ganache
    # these settings replace the defaults when running pytest
    gas_limit: 6721975
    default_contract_owner: true
    reverting_tx_gas_limit: 6721975
    revert_traceback: true
compiler:
    evm_version: null
    minify_source: false
    solc:
        version: null
        optimize: true
        runs: 200