/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IFairXYZWallets } from "../IFairXYZWallets";

export class IFairXYZWallets__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFairXYZWallets {
    return new Contract(address, _abi, signerOrProvider) as IFairXYZWallets;
  }
}

const _abi = [
  {
    inputs: [],
    name: "view_signer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "view_withdraw",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
