/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IFairXYZWalletsInterface extends ethers.utils.Interface {
  functions: {
    "view_signer()": FunctionFragment;
    "view_withdraw()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "view_signer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "view_withdraw",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "view_signer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "view_withdraw",
    data: BytesLike
  ): Result;

  events: {};
}

export class IFairXYZWallets extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IFairXYZWalletsInterface;

  functions: {
    view_signer(overrides?: CallOverrides): Promise<[string]>;

    "view_signer()"(overrides?: CallOverrides): Promise<[string]>;

    view_withdraw(overrides?: CallOverrides): Promise<[string]>;

    "view_withdraw()"(overrides?: CallOverrides): Promise<[string]>;
  };

  view_signer(overrides?: CallOverrides): Promise<string>;

  "view_signer()"(overrides?: CallOverrides): Promise<string>;

  view_withdraw(overrides?: CallOverrides): Promise<string>;

  "view_withdraw()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    view_signer(overrides?: CallOverrides): Promise<string>;

    "view_signer()"(overrides?: CallOverrides): Promise<string>;

    view_withdraw(overrides?: CallOverrides): Promise<string>;

    "view_withdraw()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    view_signer(overrides?: CallOverrides): Promise<BigNumber>;

    "view_signer()"(overrides?: CallOverrides): Promise<BigNumber>;

    view_withdraw(overrides?: CallOverrides): Promise<BigNumber>;

    "view_withdraw()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    view_signer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "view_signer()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    view_withdraw(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "view_withdraw()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
